[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "youqu"
version = "2.3.6"
authors = [
    { name = "mikigo", email = "huangmingqiang@uniontech.com" },
]

description = "deepin-autotest-framework"
readme = "youqu/README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3.7",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: OS Independent",
]

dependencies = [
]

[project.optional-dependencies]

[project.scripts]
youqu-startproject = "youqu.startproject:cli"

[tool.hatch.build.targets.wheel]
packages = [
    "/youqu",
]

[project.urls]
Source = "https://github.com/linuxdeepin/deepin-autotest-framework"
Documentation = "https://linuxdeepin.github.io/deepin-autotest-framework"
