[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "youqu"
version = "1.4.2"
authors = [
    { name = "mikigo", email = "huangmingqiang@uniontech.com" },
]

description = "deepin-autotest-framework"
readme = "youqu/README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

dependencies = [
]

#dynamic = ["version"]

[project.optional-dependencies]

[project.scripts]
youqu-startproject = "youqu.startproject:cli"

[tool.hatch.build.targets.wheel]
packages = [
    "/youqu",
]

[project.urls]
Source = "https://github.com/linuxdeepin/deepin-autotest-framework"
Documentation = "https://mikigo.github.io/youqu-docs"
